name: opera-rtc-s1-browse
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - gdal=3.10
  - numpy=2.1.2
  - pytest=8.3.3
  - pytest-cov=5.0.0
  - setuptools_scm=8.1.0
  - pip:
      - harmony-service-lib==2.2.0
      - pystac==1.11.0
