name: Static analysis

on: push

jobs:
  call-secrets-analysis-workflow:
    # Docs: https://github.com/ASFHyP3/actions
    uses: ASFHyP3/actions/.github/workflows/reusable-secrets-analysis.yml@v0.11.0

  call-flake8-workflow:
    # Docs: https://github.com/ASFHyP3/actions
    uses: ASFHyP3/actions/.github/workflows/reusable-flake8.yml@v0.11.0
    with:
      local_package_names: opera_rtc_s1_browse

  cfn-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - uses: scottbrenner/cfn-lint-action@v2.4.1
      - run: cfn-lint --info --ignore-checks W3002 cloudformation.yml
